name: Test

on:  
  push:
    tags-ignore: [ '**' ]
    
jobs:
      
  test:
    steps:
      
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.16

    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Test
      run: make test

    - name: Race
      run: make test-race

    - name: Benchmark sort
      run: make bench-sort benchtime=0.5s
